/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import code.Db;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.Toolkit;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author KSK
 */
public class NewJFrame5 extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public NewJFrame5() {
        initComponents();
        con = Db.conn();
        setIconImage(Toolkit.getDefaultToolkit().getImage(NewJFrame5.class.getResource("logo1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        old_user_name = new javax.swing.JTextField();
        old_password = new javax.swing.JPasswordField();
        old_hint = new javax.swing.JTextField();
        new_user_name = new javax.swing.JTextField();
        Confirm_New_Password = new javax.swing.JPasswordField();
        new_hint = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        system_backup = new javax.swing.JButton();
        system_reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        New_Password = new javax.swing.JPasswordField();

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KSK (Pvt) Ltd");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 249, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Old Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Old User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Old Hint");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("New User Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("New Hint");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        old_user_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(old_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, 25));

        old_password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 25));

        old_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(old_hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, 25));

        new_user_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(new_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 25));

        Confirm_New_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(Confirm_New_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 150, 25));

        new_hint.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(new_hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, 25));

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 40));

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 40));

        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 100, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Manage  User Account");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, -1));

        system_backup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        system_backup.setText("System Backup");
        jPanel1.add(system_backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 360, 40));

        system_reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        system_reset.setText("System Reset");
        jPanel1.add(system_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 360, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Confirm New Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        New_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(New_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 150, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        setSize(new java.awt.Dimension(416, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void clear() {
        old_user_name.setText(null);
        old_password.setText(null);
        old_hint.setText(null);
        new_user_name.setText(null);
        Confirm_New_Password.setText(null);
        new_hint.setText(null);

    }
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (new_user_name.getText().isEmpty()
                || Confirm_New_Password.getText().isEmpty()
                || new_hint.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Recheck The your New Values");
        } else {
            if (New_Password.getText().equals(Confirm_New_Password.getText())) {
                String old_user_name = this.old_user_name.getText();
                String old_password = this.old_password.getText();
                String old_hint = this.old_hint.getText();
                String sql1 = "select * from user_account order by id desc limit 1";
                try {
                    pst = (PreparedStatement) con.prepareStatement(sql1);
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        String user_name = rs.getString("user_name");
                        String password = rs.getString("password");
                        String hint = rs.getString("hint");
                        if (old_user_name.equals(user_name)
                                && old_password.equals(password)
                                && old_hint.equals(hint)) {

                            String new_user_name = this.new_user_name.getText();
                            String new_password = this.Confirm_New_Password.getText();
                            String new_hint = this.new_hint.getText();
                            String sql2 = "insert into user_account(user_name,password,hint)value('" + new_user_name + "','" + new_password + "','" + new_hint + "')";
                            try {
                                pst = (PreparedStatement) con.prepareStatement(sql2);
                                pst.execute();
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e);
                            }
                            clear();
                            JOptionPane.showMessageDialog(null, "Changing Done!");
                            NewJFrame4 NJ4 = new NewJFrame4();
                            NJ4.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Wrong Old Details", "Message", JOptionPane.WARNING_MESSAGE);
                        }

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Your Password Does Not Match","Message",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        NewJFrame4 NJ4 = new NewJFrame4();
        NJ4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_New_Password;
    private javax.swing.JPasswordField New_Password;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField new_hint;
    private javax.swing.JTextField new_user_name;
    private javax.swing.JTextField old_hint;
    private javax.swing.JPasswordField old_password;
    private javax.swing.JTextField old_user_name;
    private javax.swing.JButton submit;
    private javax.swing.JButton system_backup;
    private javax.swing.JButton system_reset;
    // End of variables declaration//GEN-END:variables
}
